### PR TITLE
Support ruby >= 2.3 and rails 5.x

### PR DESCRIPTION
**Pull request by maeve**
Also, drop support for ruby < 2.2 and rails < 4.1.

* Supersedes #48 
* Depends on:
  * G5/devise_g5_authenticatable#27
  * G5/g5_authenticatable_api#11
* Required for  [#144943067](https://www.pivotaltracker.com/story/show/144943067)
* Cherry-picks session timeout config changes from #51

### CODE REVIEW

**Comment by perryqh** [comment]
Great work @maeve! 🚢

**Comment by perryqh** [comment]
Nice work! This is working in https://github.com/g5search/redirects

**Comment by jcstringer** [comment]
🚢

**Comment by maeve** [comment]
This has undergone QA as part of upgrading apps to rails 5. All of the code changes since the last peer review were from independently reviewed PRs against this topic branch, so I'm gonna go ahead and merge. 🤠

**Pull request merged**
